title:              Ashutosh Shashi
email:              contact@ashutoshshashi.com
bodyTitle:          Sharing my thoughts...
description:        If you'd like to be notified when I post, 
                    or to give your valuable opinion/feedback or suggestion, 
                    subscribe to my <a href="https://twitter.com/ashutoshshashi/" style="font-weight:bold" target="_blank">Twitter feeds</a>.
author:             Ashutosh Shashi
baseurl:            "/"
url:                ""

# Social Profiles
twitter_username:   ashutoshshashi
github_username:    ashutosh-shashi
#facebook_username:  StartBootstrap
linkedin_username:  ashutoshshashi

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
